// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// R_CSF
IntegerVector R_CSF(DataFrame data, bool SloopSmooth, float ClothResolution);
RcppExport SEXP _RCSF_R_CSF(SEXP dataSEXP, SEXP SloopSmoothSEXP, SEXP ClothResolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type SloopSmooth(SloopSmoothSEXP);
    Rcpp::traits::input_parameter< float >::type ClothResolution(ClothResolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(R_CSF(data, SloopSmooth, ClothResolution));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RCSF_R_CSF", (DL_FUNC) &_RCSF_R_CSF, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RCSF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
