# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_CSF <- function(data, sloop_smooth, class_threshold, cloth_resolution, rigidness, interations, time_step) {
    .Call('_RCSF_R_CSF', PACKAGE = 'RCSF', data, sloop_smooth, class_threshold, cloth_resolution, rigidness, interations, time_step)
}

